//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Status = true;
            this.Operations = new HashSet<Operations>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<byte> CategoryId { get; set; }
        public Nullable<int> WriterId { get; set; }
        public string PublicationYear { get; set; }
        public string Publisher { get; set; }
        public string Page { get; set; }
        public Nullable<bool> Status { get; set; }
        public string BookPreview { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Writers Writers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operations> Operations { get; set; }
    }
}
